[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
[build]
  command = "npm install && npm run build"
  publish = "dist"  # Change this to your actual build output directory
  functions = "netlify/functions"
